USE discs;
INSERT INTO silasdiscs (Mold, Plastic, Brand, Weight, Speed, Glide, Turn, Fade, Slot, Category, Color, Stamp, `Sleepy Scale`)
VALUES
		('Judge', 'Fuzion', 'DD', 175, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Ice Cream DyeMax', 5),
		('Judge', 'Lucid-X', 'DD', 175, 2, 4, 0, 1, 'Putter', 'Main Bag', 'Pink', 'Oil Slick PS Bar', 7),
		('Judge', 'Lucid-X', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Backup', 'Pink', 'Rainbow PS Bar', 6),
		('Judge', 'Hybrid', 'DD', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Purple Skull', 7),
		('Judge', 'Lucid-X Chameleon', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Pink', 'Red Bar', 7),
		('Judge', 'Lucid-X Chameleon', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Pink', 'Red Bar', 7),
		('Judge', 'Fuzion', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Main Bag', 'Pink', 'Blue PS Stock Signed by EMM', 6),
		('Judge', 'Fluid', 'DD', 173, 2, 4, 0, 1, 'Putter', 'Main Bag', 'Pink', 'Silver Shatter PS Signed by PS', '7'),
		('Judge', 'Classic Hybrid', 'DD', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Blue Bar', '5'),
		('Judge', 'Classic Hybrid', 'DD', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Blue Bar', '5'),
		('Judge', 'Classic Hybrid', 'DD', 173, 2, 4, 0, 1, 'Putter', 'Main Bag', 'Pink', 'Blue Bar', '7'),
		('Judge', 'Classic Hybrid', 'DD', 173, 2, 4, 0, 1, 'Putter', 'Main Bag', 'Pink', 'Blue Bar', '6'),
		('Judge', 'Classic Hybrid', 'DD', 173, 2, 4, 0, 1, 'Putter', 'Backup', 'Black', 'Blue Bar', '7'),
		('Judge', 'Classic Blend', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Black Mini Owl', '6'),
		('Judge', 'Classic Blend', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Black Mini Owl', '6'),
		('Judge', 'Prime', 'DD', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'Blue', 'Black Mini Owl', '5'),
		('Judge', 'Prime', 'DD', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'Blue', 'Black Mini Owl', '5'),
		('Judge', 'Prime', 'DD', 175, 2, 4, 0, 1, 'Putter', 'Collection', 'Blue', 'Gold Bar', '5'),
		('Judge', 'Prime', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Red', 'Silver Misprint Bar', '6'),
		('Judge', 'Prime', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Red', 'Silver Misprint Bar', '6'),
		('Judge', 'Prime', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Red', 'Silver Misprint Bar', '6'),
		('Judge', 'Prime', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Red', 'Silver Misprint Bar Glow Tape', '6'),
		('Judge', 'Prime Burst', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Pink', 'Silver Misprint Bar', '5'),
		('Judge', 'Prime Burst', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Pink', 'Silver Misprint Bar', '5'),
        ('Judge', 'Classic Burst', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Yellow', 'Silver Misprint', '7'),
		('Harp', 'BT Medium', 'WS', 173, 4, 3, 0, 3, 'Putter', 'Main Bag', 'Blue', 'Pink Shatter DGPT', 7),
		('Harp', 'VIP Moonshine', 'WS', 176, 4, 3, 0, 3, 'Putter', 'Main Bag', 'Green', 'Red Ricky 2x', 7),
		('Justice', 'Lucid Glimmer', 'DD', 169, 5, 0, .5, 3, 'Mid-Range', 'Main Bag', 'Pink', 'Blue Lady Justice', 7),
		('EMAC Truth', 'Lucid-X Glimmer', 'DD', 180, 5, 5, 0, 2, 'Mid-Range', 'Main Bag', 'Pink', '2021 TS', 7),
		('EMAC Truth', 'Lucid-X Moonshine', 'DD', 180, 5, 5, 0, 2, 'Mid-Range', 'Main Bag', 'Pink', '2020 TS V4', 7),
		('Fuse', 'Opto-X Glimmer', 'L64', 178, 5, 6, '-1', 0, 'Mid-Range', 'Main Bag', 'Pink', '2021 TS V2', 7),
		('Fuse', 'Opto', 'L64', 178, 5, 6, '-1', 0, 'Mid-Range', 'Main Bag', 'Orange', 'Black Witch', 5),
		('Explorer', 'Gold Burst', 'L64', 175, 7, 5, 0, 2, 'Fairway Driver', 'Main Bag', 'Orange', '2018 AM Match Play', 6),
		('Explorer', 'Opto-X Glimmer', 'L64', 176, 7, 5, 0, 2, 'Fairway Driver', 'Main Bag', 'Pink', '2020 TS V3', 7),
		('Escape', 'Fuzion', 'DD', 173, 9, 5, '-1', 2, 'Control Driver', 'Main Bag', 'Red', 'Purple HE Good Energy', 7),
		('Hatchet', 'VIP', 'WS', 169, 9, 6, '-2', 1, 'Control Driver', 'Main Bag', 'Pink', 'Green Stock', 7),
		('Felon', 'Lucid-X', 'DD', 176, 9, 3, 0.5, 4, 'Control Driver', 'Main Bag', 'Pink', '2019 TS', 6),
		('Felon', 'Lucid-X Glimmer', 'DD', 176, 9, 3, 0.5, 4, 'Control Driver', 'Main Bag', 'Pink', '2021 EO TS', 6),
		('Trespass', 'Fuzion', 'DD', 175, 12, 5, '-0.5', 3, 'Distance Driver', 'Main Bag', 'White', 'Candy Cane DyeMax', 6),
		('Trespass', 'Hybrid', 'DD', 173, 12, 5, '-0.5', 3, 'Distance Driver', 'Main Bag', 'Pink', 'PMBF La Paz', 7),
		('Rive', 'Royal-Proto', 'L64', 175, 13, 5, 0, 3.5, 'Distance Driver', 'Main Bag', 'Orange', 'Prototype', 6),
		('Rive', 'Grand', 'L64', 175, 13, 5, 0, 3.5, 'Distance Driver', 'Main Bag', 'Blue', 'Silver Stock', 8),
		('Ballista Pro', 'Opto Air', 'L64', 158, 14, 4, 0, 3, 'Distance Driver', 'Main Bag', 'Orange', 'Misprint Stock', 7),
		('Ballista Pro', 'Opto Moonshine', 'L64', 176, 14, 4, 0, 3, 'Distance Driver', 'Main Bag', 'Pink', 'Gold Bar', 7),
		('Ballista Pro', 'Gold', 'L64', 174, 14, 4, 0, 3, 'Distance Driver', 'Main Bag', 'White', 'P Hill DyeMax', 5),
		('Ballista', 'Opto', 'L64', 169, 14, 5, '-1', 3, 'Distance Driver', 'Main Bag', 'Orange', 'Stock', 5),
		('Ballista', 'Opto Sparkle', 'L64', 174, 14, 5, -1, 3, 'Distance Driver', 'Main Bag', 'Orange', 'Fall Fling 2 2022', 8),
		('Fierce', 'Rubber Blend', 'DCRFT', 171, 3, 4, -2, 0, 'Putter', 'Emily', 'Purple', 'Blue Shatter Tron', 7),
		('Fierce', 'Rubber Blend', 'DCRFT', 171, 3, 4, -2, 0, 'Putter', 'Emily', 'Orange', 'Purple Shatter Tron', 7),
		('Fierce', 'Big Z', 'DCRFT', 171, 3, 4, -2, 0, 'Putter', 'Emily', 'Red', 'Rainbow Lion', 8),
		('Fierce', 'Big Z', 'DCRFT', 171, 3, 4, -2, 0, 'Putter', 'Emily', 'Red', 'Rainbow Lion', 10),
		('Luna', 'Big Z', 'DCRFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Yellow', 'Black PMB Luna', 9),
		('Luna', 'Big Z', 'DCRFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Yellow', 'Black PMB Luna', 8),
		('Luna', 'Z', 'DCRFT', NULL, 3, 3, 0, 3, 'Putter', 'Emily', 'White', 'Black PMB TS 2020', 8),
		('Luna', 'Z', 'DCRFT', 170, 3, 3, 0, 3, 'Putter', 'Emily', 'Pink', 'Black PMB TS 2020', 8),
		('Luna', 'Metallic Z', 'DCRFT', 170, 3, 3, 0, 3, 'Putter', 'Emily', 'Pink', 'Silver Flower PMB TS 2021', 9),
		('Luna', 'Metallic Z', 'DCRFT', 170, 3, 3, 0, 3, 'Putter', 'Emily', 'Pink', 'Silver Sparkle PMB TS 2021', 10),
		('Luna', 'Special Blend', 'DCRFT', NULL, 3, 3, 0, 3, 'Putter', 'Emily', 'Purple', 'Green Shatter First Run', 6),
		('Luna', 'Jawbreaker', 'DCRFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Purple', 'Blue JoeMez Armadillo', 8),
		('Luna', 'Jawbreaker', 'DCRFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Pink', 'Rainbow JoeMez Armadillo', 8),
		('Luna', 'Jawbreaker', 'DCRFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Blue', 'Wite Slomez JoeMez', 7),
		('Luna', 'Jawbreaker', 'DCRFT', NULL, 3, 3, 0, 3, 'Putter', 'Emily', 'Green', 'Rainbow Slomez JoeMez', 7),
		('Luna', 'Rubber Blend', 'DCRFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Green', 'Blue OTB UFO', 7),
		('Luna', 'Rubber Blend', 'DCRFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Grey', 'Rainbow PMB Stock', 7),
		('Luna', 'Rubber Blend', 'DCRFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Black', 'Rainbow PMB Stock', 6),
		('BangerGT', 'Crystal Flx Sparkle', 'DCRFT', NULL, 3, 3, 0, 3, 'Putter', 'Emily', 'Blue', 'Cheetah Ledgestone 2021', 8),
		('Fuse', 'Lucid-X', 'L64', 180, 5, 6, '-1', 0, 'Mid-Range', 'Backup', 'Pink', 'Silver 2020 TS V1', 7),
		('Fuse', 'Opto Sparkle', 'L64', 175, 5, 6, '-1', 0, 'Mid-Range', 'Collection', 'Clear', 'Pink 10 Year', 9),
		('Pure', 'Zero Hybrid', 'L64', 174, 3, 3, '-1', 1, 'Putter', 'Collection', 'White', 'Black Royal Box', 9),
		('Pure', 'Opto Sparkle', 'L64', 174, 3, 3, '-1', 1, 'Putter', 'Collection', 'Silver', 'Skull Decodye', 7),
		('Faith', 'Sense Prototype', 'L64', 173, 2, 3, 0, 1, 'Putter', 'Collection', 'Pink', 'Black Royal Prototype', 8),
		('Destroyer', 'Shimmer Star', 'Innova Disc Golf', 175, 12, 5, -1, 3, 'Distance Driver', 'Collection', 'Gold', 'USDGC 2020', 10),
		('Explorer', 'Opto Glimmer', 'L64', 174, 7, 5, 0, 2, 'Fairway Driver', 'Collection', 'Clear', 'Boat Decodye Royal Box', 9),
		('EMAC Judge', 'Classic Blend', 'DD', 173, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Blue First RunMini', 10),
		('Envy', 'Electron?', 'AXM', 170, 3, 3, 0, 2, 'Putter', 'Collection', 'Purple', 'MVP OPEN 2020', '8'),
		('EMAC Truth', 'Lucid', 'DD', 174, 5, 5, 0, 2, 'Mid-Range', 'Collection', 'Pink', '2021 DDO Signed by PMB, EMM, HK', 9),
		('Hades', 'ESP', 'DCRFT', NULL, 12, 6, -3, 2, 'Distance Driver', 'Collection', 'Pink', 'Silver Money Prototype', 8),
		('Sol', 'Z', 'DCRFT', 173, 4, 5, -3, 0, 'Mid-Range', 'Emily', 'Yellow', 'Silver Stock', 6),
		('Judge', 'Fuzion', 'DD', 176, 2, 4, 0, 1, 'Putter', 'Side Bag', 'Pink', 'Red PS Stock', 6),
		('Judge', 'Fluid', 'DD', 173, 2, 4, 0, 1, 'Putter', 'Side Bag', 'Pink', 'Silver Star PS Signed by PS', '7'),
		('Judge', 'Classic Hybrid', 'DD', 173, 2, 4, 0, 1, 'Putter', 'Side Bag', 'Yellow', 'Purple Bar', '6'),
		('Justice', 'Lucid Sparkle', 'DD', 171, 5, 0, .5, 3, 'Mid-Range', 'Side Bag', 'Pink', 'White TT 2020 Van', 6),
		('Harp', 'Tournament', 'WS', 173, 4, 3, 0, 3, 'Putter', 'Side Bag', 'Pink', 'Pink Kannel', 6),
		('EMAC Truth', 'Lucid-X Moonshine', 'DD', 180, 5, 5, 0, 2, 'Mid-Range', 'Side Bag', 'Pink', '2020 TS V4', 7),
		('Fuse', 'Opto', 'L64', 177, 5, 6, '-1', 0, 'Mid-Range', 'Side Bag', 'Pink', 'Misprint Stock', 8),
		('Explorer', 'Special Edition', 'L64', 173, 7, 5, 0, 2, 'Fairway Driver', 'Side Bag', 'Orange', 'Gold Special Edition', 6),
		('Felon', 'Lucid Glimmer', 'DD', 174, 9, 3, 0.5, 4, 'Control Driver', 'Side Bag', 'Pink', 'Blue HE OS', 6),
		('Trespass', 'Fuzion', 'DD', 175, 12, 5, '-0.5', 3, 'Distance Driver', 'Backup', 'White', 'Beaver Ranch DyeMax', 6),
		('Enforcer', 'Lucid Sparkle', 'DD', 172, 12, 4, .5, 4, 'Distance Driver', 'Side Bag', 'Pink', 'Gold Stock', 7),
		('Zone', 'Jawbreaker', 'DCRFT', 168, 4, 3, 0, 3, 'Putter', 'Emily', 'Yellow', 'Black GMC ', 7),
		('Zone', 'Jawbreaker', 'DCRFT', 173, 4, 3, 0, 3, 'Putter', 'Emily', 'Purple', 'Silver Stock ', 7),
		('Zone', 'Z', 'DCRFT', 173, 4, 3, 0, 3, 'Putter', 'Emily', 'Pink', 'Silver Stock ', 7),
		('Zone', 'ESP', 'DCRFT', 173, 4, 3, 0, 3, 'Putter', 'Emily', 'Green', 'Blue Stock ', 8),
		('Zone', 'ESP', 'DCRFT', 173, 4, 3, 0, 3, 'Putter', 'Emily', 'Blue', 'Blue Stock ', 8),
		('Zone', 'UV Photon', 'DCRFT', 165, 4, 3, 0, 3, 'Putter', 'Emily', 'Grey', 'Blue FDN', 8),
		('Zone', 'UV Photon', 'DCRFT', 165, 4, 3, 0, 3, 'Putter', 'Emily', 'Grey', 'Blue FDN', 8),
		('Sol', 'Z', 'DCRFT', Null, 4, 5, -3, 0, 'Mid-Range', 'Emily', 'Yellow', 'Blacl PP5x', 7),
		('Sol', 'Z', 'DCRFT', 173, 4, 5, -3, 0, 'Mid-Range', 'Emily', 'Yellow', 'Red First Run', 5),
		('Sol', 'Z Metallic', 'DCRFT', 173, 4, 5, -3, 0, 'Mid-Range', 'Emily', 'Green', 'Blue PP Triangle', 8),
		('Sol', 'Z Metallic', 'DCRFT', 173, 4, 5, -3, 0, 'Mid-Range', 'Emily', 'Grey', 'Blue PP Triangle', 9),
		('Sol', 'Z Metallic', 'DCRFT', 173, 4, 5, -3, 0, 'Mid-Range', 'Emily', 'Blue', 'Silver PP Triangle', 10),
		('BangerGT', 'Crystal Flx Sparkle', 'DCRFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Blue', 'Cheetah Ledgestone 2021', 9),
		('BangerGT', 'Jawbreaker', 'DCRFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Yellow', 'Silver Shatter Stock', 7),
		('BangerGT', 'Jawbreaker', 'DCRFT', 171, 3, 3, 0, 3, 'Putter', 'Emily', 'Purple', 'Green Stock', 8),
		('BangerGT', 'Ti Swirl', 'DCRFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Green', 'Green LDG 2020', 7),
		('BangerGT', 'X Soft', 'DCRFT', null, 3, 3, 0, 3, 'Putter', 'Emily', 'Orange', 'Silver Shatter', 6),
		('Harp', 'Origo Burst', 'WS', 173, 4, 3, 0, 3, 'Putter', 'Backup', 'Pink', 'Misprint Stock', 6),
		('Harp', 'BT Moonshine', 'WS', 175, 4, 3, 0, 3, 'Putter', 'Backup', 'Blue', 'Idelwild DGPT 2020', 6),
		('Harp', 'BT Hard', 'WS', 175, 4, 3, 0, 3, 'Putter', 'Backup', 'White', 'DDO 2021', 6),
		('Justice', 'Lucid Sparkle', 'DD', 175, 5, 0, .5, 3, 'Mid-Range', 'Backup', 'Pink', 'JR ME DG', 6),
		('Justice', 'Prim', 'DD', 171, 5, 0, .5, 3, 'Mid-Range', 'Backup', 'Red', 'Stock', 6),
		('Warship', 'Tournament', 'WS', 177, 5, 6, 0, 1, 'Mid-Range', 'Emily', 'White', 'Demon DyeMax', 7),
		('Warship', 'Tournament', 'WS', 167, 5, 6, 0, 1, 'Mid-Range', 'Emily', 'White', 'Gold Stock Old Flight Numbers', 7),
		('Warship', 'VIP', 'WS', 174, 5, 6, 0, 1, 'Mid-Range', 'Emily', 'White', 'Fly Guy', 8),
		('EMAC Truth', 'Moonshine', 'DD', 178, 5, 5, 0, 2, 'Mid-Range', 'Backup', 'Clear', 'Red Stock', 7),
		('EMAC Truth', 'Moonshine', 'DD', 178, 5, 5, 0, 2, 'Mid-Range', 'Emily', 'Clear', 'Red Stock', 7),
		('EMAC Truth', 'Fuzion Burst', 'DD', 171, 5, 5, 0, 2, 'Mid-Range', 'Emily', 'Blue', 'Gold Stock', 6),
		('EMAC Truth', 'Lucid-X Glimmer', 'DD', 174, 5, 5, 0, 2, 'Mid-Range', 'Emily', 'Blue', 'TS 2020 ', 6),
		('EMAC Truth', 'Lucid Sparkle', 'DD', 172, 5, 5, 0, 2, 'Mid-Range', 'Backup', 'Pink', 'Gold Stock', 7),
		('Mako3', 'Star', 'INVA', 177, 5, 5, 0, 0, 'Mid-Range', 'Emily', 'White', 'Misprint Stock', 7),
		('Shark', 'DX', 'INVA', null, 4, 4, 0, 2, 'Mid-Range', 'Emily', 'Purple', 'Sugarbush', 6),
		('Condor', 'Star', 'INVA', null, 3, 4, 0, 2, 'Mid-Range', 'Collection', 'White', 'Green Stock', 7),
		('Trust', 'Grand', 'L64', 174, 5, 5, 0, 2, 'Mid-Range', 'Collection', 'Blue', 'Silver Prototype', 8),
		('Beetle', 'Opto', 'L64', 174, 1, 7, -1, 0, 'Mid-Range', 'Collection', 'Pink', 'Blue L64 Skull', 7),
		('Drone', 'Big Z', 'DCRFT', null, 5, 3, 1, 4, 'Mid-Range', 'Emily', 'Green', 'Black Stock', 6),
		('Verdict', 'Lucid-X', 'DD', 180, 5, 4, 0, 3.5, 'Mid-Range', 'Collection', 'Pink', 'TS 2020', 7),
		('Buzzz', 'Crystal', 'DCRFT', 177, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Green', 'Blue PP OTB Bee', 9),
		('Buzzz', 'Crystal', 'DCRFT', 177, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Clear', 'Pink PP OTB Bee', 9),
		('Buzzz', 'Z', 'DCRFT', Null, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Green', 'Red PP TS 2020', 8),
		('Buzzz', 'Z', 'DCRFT', Null, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Blue', 'Blue PP TS 2020', 8),
		('Buzzz', 'Z', 'DCRFT', Null, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Green', 'Red PP TS 2020', 8),
		('Buzzz', 'Z', 'DCRFT', Null, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Green', 'Wonderbread MU SF 2021', 7),
		('Buzzz', 'ESP', 'DCRFT', Null, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Blue', 'NEADGC 20201', 8),
		('Buzzz', 'Crystal', 'DCRFT', 177, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Pink', 'Blue PP OTB Bee', 8),
		('Archer', 'Big Z', 'DCRFT', Null, 5, 4, -4, 1, 'Mid-Range', 'Emily', 'Green', 'Oils Slick Stock', 7),
		('Reactor', 'Eclipse Glow', 'MVP', 176, 5, 5, -.5, 1.5, 'Mid-Range', 'Collection', 'Green', 'Silver EK ES 2021', 8),
		('Compass', 'Gold', 'L64', 179, 5, 5, 0, 1, 'Mid-Range', 'Emily', 'White', 'Pizza Kitty DyeMax', 7),
		('Diamond', 'Gold Orbit', 'L64', 151, 8, 6, -3, 1, 'Fairway Driver', 'Emily', 'Pink', 'Purple 10 Year', 7),
		('Diamond', 'Opto', 'L64', 171, 8, 6, -3, 1, 'Fairway Driver', 'Emily', 'Blue', 'Green and Red Misprint', 8),
		('Diamond', 'Opto', 'L64', 154, 8, 6, -3, 1, 'Fairway Driver', 'Emily', 'White', 'Blue Stock', 6),
		('Sapphire', 'Opto', 'L64', 157, 10, 6, -2, 1.5, 'Control Driver', 'Emily', 'Pink', 'Blue Stock', 8),
		('Sapphire', 'Opto Sparkle', 'L64', 155, 10, 6, -2, 1.5, 'Control Driver', 'Emily', 'Green', 'Green Reindeer', 8),
		('Sapphire', 'Gold', 'L64', 159, 10, 6, -2, 1.5, 'Control Driver', 'Emily', 'Red', 'Blue Bear', 8),
		('Sapphire', 'Gold Burst', 'L64', 163, 10, 6, -2, 1.5, 'Control Driver', 'Emily', 'Blue', 'Diamond', 8),
		('Ballista Pro', 'Opto Chameleon', 'L64', 176, 14, 4, 0, 3, 'Distance Driver', 'Backup', 'White', 'Red Royal Box', 8),
		('Ballista', 'Opto-X Chameleon', 'L64', 175, 14, 4, 0, 3, 'Distance Driver', 'Backup', 'Pink', 'Red Special', 8),
		('Ballista', 'Opto-X Chameleon', 'L64', 175, 14, 4, 0, 3, 'Distance Driver', 'Backup', 'Pink', 'Red Special', 8),
		('River', 'Opto', 'L64', 173, 7, 7, -1, 1, 'Fairway Driver', 'Collection', 'White', 'Black Misprint Stock', 8),
		('River', 'Opto', 'L64', 171, 7, 7, -1, 1, 'Fairway Driver', 'Collection', 'White', 'White Misprint Stock', 8),
		('River', 'Opto Sparkle', 'L64', 174, 7, 7, -1, 1, 'Fairway Driver', 'Emily', 'Red', 'Blue Stock', 8),
		('River', 'Opto-X', 'L64', Null, 7, 7, -1, 1, 'Fairway Driver', 'Collection', 'Pink', 'Red 10 Year', 8),
		('River', 'Opto-X', 'L64', Null, 7, 7, -1, 1, 'Fairway Driver', 'Collection', 'Pink', 'Green 10 Year', 7),
		('Hatchet', 'VIP', 'WS', 176, 9, 6, '-2', 1, 'Control Driver', 'Collection', 'White', 'Black Misptint Underworld', 9),
		('Musket', 'Lucid', 'L64', 174, 9, 6, '-2', 1, 'Control Driver', 'Collection', 'White', 'Purple Pirate', 8),
		('Musket', 'Lucid', 'L64', 174, 9, 6, '-2', 1, 'Control Driver', 'Collection', 'Green', 'Silver and Blue Misprint', 8),
		('Explorer', 'Opto', 'L64', 175, 7, 5, 0, 2, 'Fairway Driver', 'Collection', 'White', 'Gold and Silver Misprint Stock', 9),
		('Explorer', 'Opto', 'L64', 175, 7, 5, 0, 2, 'Fairway Driver', 'Collection', 'White', 'Gold and Silver Misprint Stock', 9),
		('Raider', 'Lucid', 'DD', 176, 13, 5, '-0.5', 3, 'Distance Driver', 'Collection', 'White', 'Blue Misprint Stock', 9),
		('Raider', 'Fuzion', 'DD', 174, 13, 5, '-0.5', 3, 'Distance Driver', 'Collection', 'Pink', 'Gold Yin Yang', 7),
		('Raider', 'Fuzion', 'DD', 174, 13, 5, '-0.5', 3, 'Distance Driver', 'Collection', 'Pink', 'Gold Yin Yang', 8),
		('Raider', 'Bio Fuzion', 'DD', 173, 13, 5, '-0.5', 3, 'Distance Driver', 'Collection', 'Pink', 'Silver Am Match Play', 5),
		('Judge', 'Fuzion', 'DD', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Green Misprint Lucid', 9),
		('Judge', 'Fuzion', 'DD', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Green Misprint Lucid', 9),
		('Pure', 'Zero Moonshine', 'L64', 176, 3, 3, '-1', 1, 'Putter', 'Collection', 'White', 'Red 2020 AM Match Play', 9),
		('Trespass', 'Fuzion', 'DD', 174, 12, 5, '-0.5', 3, 'Distance Driver', 'Backup', 'White', 'BB  Phill DyeMax', 7),
		('Trespass', 'Lucid', 'DD', 173, 12, 5, '-0.5', 3, 'Distance Driver', 'Backup', 'Pink', 'Gold Stock', 8),
		('Trespass', 'Lucid', 'DD', 173, 12, 5, '-0.5', 3, 'Distance Driver', 'Backup', 'Pink', 'Silver and Red Misprint Stock', 9),
		('Trespass', 'Lucid', 'DD', 175, 12, 5, '-0.5', 3, 'Distance Driver', 'Backup', 'White', 'Green Reindeer', 8),
		('Trespass', 'Lucid', 'DD', 173, 12, 5, '-0.5', 3, 'Distance Driver', 'Backup', 'Yellow', 'Purple Skull/Dogs', 7),
		('Trespass', 'Lucid', 'DD', 175, 12, 5, '-0.5', 3, 'Distance Driver', 'Backup', 'Blue', 'Wonderland Brewing', 6),
		('Trespass', 'Prime Burst', 'DD', 175, 12, 5, '-0.5', 3, 'Distance Driver', 'Backup', 'Pink', 'Green and Purple Misprint Stock', 9),
		('Explorer', 'Opto-X Moonshine', 'L64', 175, 7, 5, 0, 2, 'Fairway Driver', 'Backup', 'Pink', 'Wiped 2020 TS V4', 8),
		('Explorer', 'Opto-X Glimmer', 'L64', 176, 7, 5, 0, 2, 'Fairway Driver', 'Backup', 'Pink', '2020 TS V3', 8),
		('Explorer', 'Opto-X Glimmer', 'L64', 175, 7, 5, 0, 2, 'Fairway Driver', 'Backup', 'Pink', '2020 TS V2', 8),
		('Explorer', 'Grip', 'L64', 176, 7, 5, 0, 2, 'Fairway Driver', 'Backup', 'Pink', 'Blue Bar', 5),
		('Escape', 'Lucid', 'DD', 175, 9, 5, '-1', 2, 'Control Driver', 'Side Bag', 'Pink', 'Blue Stock', 6),
		('Escape', 'Prime Burst', 'DD', 173, 9, 5, '-1', 2, 'Control Driver', 'Backup', 'Pink', 'Red and Silver Misprint Stock', 6),
		('Escape', 'Prime Burst', 'DD', 173, 9, 5, '-1', 2, 'Control Driver', 'Backup', 'Pink', 'Red and Silver Misprint Stock', 6),
		('Escape', 'Prime Burst', 'DD', 173, 9, 5, '-1', 2, 'Control Driver', 'Backup', 'Blue', 'Red Stock', 5),
		('Raketen', 'Opto Hex', 'L64', 169, 15, 4, -2, 3, 'Distance Driver', 'Collection','Blue', 'Stock', 5),
		('Raptor', 'Z', 'DCRFT', 171, 9, 4, 0, 3, 'Control Driver', 'Emily', 'Yellow', 'Silver Stock', 8),
		('Jade', 'Opto', 'L64', 156, 9, 6, -2, 1, 'Control Driver', 'Emily', 'Blue', 'White DDO 2021', 7),
		('TeeBird3', 'GStar', 'INVA', 157, 8, 4, 0, 2, 'Fairway Driver', 'Emily', 'Green', 'Silver Stock', 8),
		('TeeBird3', 'GStar', 'INVA', 157, 8, 4, 0, 2, 'Fairway Driver', 'Emily', 'Green', 'Silver Stock', 8),
		('Leopard', 'GStar', 'INVA', Null, 6, 5, -2, 1, 'Fairway Driver', 'Emily', 'Orange', 'Multi Color Stock', 8),
		('Leopard', 'Star', 'INVA', 172, 6, 5, -2, 1, 'Fairway Driver', 'Emily', 'Blue', 'Yellow Stock', 8),
		('Leopard', 'Pro', 'INVA', 175, 6, 5, -2, 1, 'Fairway Driver', 'Emily', 'White', 'TyeDye', 4),
		('Leopard', 'Pro', 'INVA', Null, 6, 5, -2, 1, 'Fairway Driver', 'Emily', 'Blue', 'Faded Stock', 4),
		('Roadrunner', 'Star', 'INVA', 149, 9, 5, -4, 1, 'Control Driver', 'Emily', 'Orange', 'Black GB Stock', 8),
		('Roadrunner', 'Star', 'INVA', 170, 9, 5, -4, 1, 'Control Driver', 'Emily', 'Blue', 'Purple GB Stock', 7),
		('Roadrunner', 'Star', 'INVA', 150, 9, 5, -4, 1, 'Control Driver', 'Emily', 'Yellow', 'Blue F2', 4),
		('Roadrunner', 'Champion', 'INVA', 170, 9, 5, -4, 1, 'Control Driver', 'Emily', 'Red', 'Blue Wondervu', 8),
		('Sergeant', 'Lucid', 'DD', 173, 11, 3, 0.5, 4, 'Distance Driver', 'Collection', 'Pink', 'Silver First Run', 6),		
		('Sergeant', 'Lucid', 'DD', 173, 11, 3, 0.5, 4, 'Distance Driver', 'Collection', 'Orange', 'USA First Run', 8),
		('Grace', 'Royal-Proto', 'L64', 173, 11, 6, -1, 2, 'Distance Driver', 'Collection', 'Orange', 'Prototype', 8),
		('Rival', 'Pinnacle', 'LGCY', 175, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Pink', 'Blue Stock', 8),
		('Rival', 'Icon', 'LGCY', 172, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Purple', 'Gold Stock', 7),
		('Undertaker', 'Z', 'DCRFT', Null, 9, 5, '-1', 2, 'Control Driver', 'Emily', 'Orange', 'Silver MG 2020 TS', 7),
		('Undertaker', 'ESP', 'DCRFT', Null, 9, 5, '-1', 2, 'Control Driver', 'Emily', 'Pink', 'Silver MU SF 2021', 7),
		('Maverick', 'Special Edition', 'DD', 175, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Pink', 'Black Stock', 7),
		('Maverick', 'Lucid', 'DD', 169, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Purple', 'Black and Silver Misprint Stock', 7),
		('Sapphire', 'Opto Chameleon', 'L64', 157, 10, 6, -2, 1.5, 'Control Driver', 'Emily', 'Blue', 'Blue First Run', 8),
		('Culverin', 'Opto', 'L64', 175, 9, 5, -.5, 3, 'Control Driver', 'Collection', 'Grey', 'Grey Stock', 7),
		('Culverin', 'Opto Air', 'L64', 159, 9, 5, -.5, 3, 'Control Driver', 'Collection', 'Red', 'Purple Stock', 8),
		('War Horse', 'VIP', 'WS', 170, 13, 4, 0, 4, 'Distance Driver', 'Collection', 'Blue', 'Green and Silver Misprint', 9),
		('Convict', 'Lucid', 'DD', 174, 9, 5, -.5, 3, 'Control Driver', 'Collection', 'Yellow', 'Purple and BlueDisc Golf', 8),
		('Pioneer ', 'Gold Burst', 'L64', 173, 9, 3, 0, 4, 'Control Driver', 'Collection', 'Blue', 'Silver and Purple Am Match Play', 8),
		('HellFire', 'Pro-Line', 'DGA', 171, 10, 3, 0, 5, 'Control Driver', 'Collection', 'Blue', 'Pink DELA', 8),
		('Maverick', 'Lucid-X Chameleon', 'DD', 176, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Red', '2021 ZM TS', 7),
		('Maverick', 'Lucid', 'DD', 172, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Clear', 'Purple and Silver Misprint Stock', 7),
		('Maverick', 'Lucid', 'DD', 172, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Clear', 'Purple and Silver Misprint Stock', 7),
		('Slammer', 'Lucid', 'DD', 174, 3, 2, 0, 3, 'Putter', 'Collection', 'Red', 'Gold Stock', 7),
		('Slammer', 'Classic Blend', 'DD', 175, 3, 2, 0, 3, 'Putter', 'Collection', 'Whie', 'Gold Stock', 5),
		('Breakout', 'Prime Burst', 'DD', 157, 8, 5, -1, 1.5, 'Fairway Driver', 'Collection', 'Pink', 'Silver Stock', 3),
		('Boatman', 'VIP', 'WS', 171, 11, 5, 0, 2, 'Distance Driver', 'Collection', 'Orange', 'Faded Stock', 6),
		('Lace', Null, 'Vibram', 172, 14, 6, -1, 1, 'Distance Driver', 'Collection', 'Green', Null, 4),
		('Vamp', Null, 'Vibram', 158, 7, 5, -2, 1, 'Fairway Driver', 'Collection', 'White', Null, 5),
		('Golem', ' StayPut', 'Divergent', 174, 4, 2, 0, 3.5, 'Putter', 'Collection', 'Black', 'White Stock', 8),
		('#2 Driver', 'Lightning Standard', 'Lightning Discs', Null, 8, 5, -2, 2, 'Fairway Driver', 'Collection', 'Clear', 'Faded Blue Stock', 3),
		('Avenger SS', 'Z', 'Discraft', Null, 10, 5, -3, 1, 'Control Driver', 'Collection', 'Orange', 'Black Stock', 9),
		('Reaper', 'Elite Z', 'Discraft', Null, 8, 3, 0, 4, 'Fairway Driver', 'Collection', 'TyeDye', 'Silver Stock', 7),
		('Machete', 'Titanium', 'Discraft', Null, 11, 4, 0, 4, 'Distance Driver', 'Collection', 'Blue', 'Open at Belton 2019', 9),
		('FLICK', 'Z', 'Discraft', 173, 12, 3, 1, 5, 'Distance Driver', 'Collection', 'Red', 'White Stock', 9),
		('Relay', 'Neutron', 'MVP', 158, 6, 5, -2, 1, 'Fairway Driver', 'Collection', 'White', 'PDGA Membership', 9),
		('Destroyer', 'Star', 'Innova Disc Golf', Null, 12, 5, -1, 3, 'Distance Driver', 'Collection', 'Purple', 'Silver PMB 4x', 7),
		('Destroyer', 'Star', 'Innova Disc Golf', 169, 12, 5, -1, 3, 'Distance Driver', 'Collection', 'White', 'Bottom Stamp Santa Cruz', 6),
		('Destroyer', Null, 'Innova Disc Golf', 175, 12, 5, -1, 3, 'Distance Driver', 'Collection', 'White', 'Dragons Breath Open 2018', 7),
		('Destroyer', 'Pro', 'Innova Disc Golf', 168, 12, 5, -1, 3, 'Distance Driver', 'Collection', 'Orange', 'Gold Misprint', 7),
		('Firebird', 'Color Glow', 'Innova Disc Golf', 175, 9, 3, 0, 4, 'Control Driver', 'Collection', 'Blue', 'Blue NS TS 2017', 6),
		('Valkyrie', 'Star', 'Innova Disc Golf', 150, 9, 4, -2, 2, 'Control Driver', 'Collection', 'White', 'Pink Faded Stock', 6),
		('Katana', 'Blizzard Champion', 'Innova Disc Golf', 168, 13, 5, -3, 3, 'Distance Driver', 'Collection', 'Yellow', 'Red Stock', 7),
		('Tern', 'Champion', 'Innova Disc Golf', Null, 12, 6, -3, 2, 'Distance Driver', 'Collection', 'Red', 'Faded Stock', 7),
		('Tern', 'Champion', 'Innova Disc Golf', Null, 12, 6, -3, 2, 'Distance Driver', 'Collection', 'Clear', 'Dyed', 7),
		('Wraith', 'DX', 'Innova Disc Golf', 172, 11, 5, -1, 3, 'Distance Driver', 'Collection', 'Orange', 'Black Stock', 6),
		('Wraith', 'Pro', 'Innova Disc Golf', 169, 11, 5, -1, 3, 'Distance Driver', 'Collection', 'yellow', 'Orange Stock', 6),
		('Boss', 'Pro', 'Innova Disc Golf', 175, 13, 5, -1, 3, 'Distance Driver', 'Collection', 'White', 'Black Stock Gangster', 6),
		('Boss', 'Pro', 'Innova Disc Golf', 175, 13, 5, -1, 3, 'Distance Driver', 'Collection', 'Black', 'Silver Stock', 7),
		('Boss', 'Blizzard Champion', 'Innova Disc Golf', Null, 13, 5, -1, 3, 'Distance Driver', 'Collection', 'Black', 'Silver DW Stock', 6),
		('Boss', 'Champion', 'Innova Disc Golf', Null, 13, 5, -1, 3, 'Distance Driver', 'Collection', 'TyeDye', 'Silver Stock', 6),
		('Cro', 'Star', 'Innova Disc Golf', 175, 5, 3, 0, 2, 'Mid-Range', 'Collection', 'Yellow', 'Silver First Run', 7),
        ('D1', '750G', 'Prodigy Disc Golf', 174, 12, 5, 0, 3, 'Distance Driver', 'Collection', 'Yellow', 'MO TS 2020', 8)
        ;