USE discs;
INSERT INTO silasdiscs (Mold, Plastic, Brand, Weight, Speed, Glide, Turn, Fade, Slot, Category, Color, Stamp, `Sleepy Scale`)
VALUES
		('Judge', 'Fuzion', 'DYNAMIC DISCS', 175, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Ice Cream DyeMax', 5),
		('Judge', 'Lucid-X', 'DYNAMIC DISCS', 175, 2, 4, 0, 1, 'Putter', 'Main Bag', 'Pink', 'Oil Slick PS Bar', 7),
		('Judge', 'Lucid-X', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Backup', 'Pink', 'Rainbow PS Bar', 6),
		('Judge', 'Hybrid', 'DYNAMIC DISCS', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Purple Skull', 7),
		('Judge', 'Lucid-X Chameleon', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Pink', 'Red Bar', 7),
		('Judge', 'Lucid-X Chameleon', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Pink', 'Red Bar', 7),
		('Judge', 'Fuzion', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Main Bag', 'Pink', 'Blue PS Stock Signed by EMM', 6),
		('Judge', 'Fluid', 'DYNAMIC DISCS', 173, 2, 4, 0, 1, 'Putter', 'Main Bag', 'Pink', 'Silver Shatter PS Signed by PS', 7),
		('Judge', 'Classic Hybrid', 'DYNAMIC DISCS', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Blue Bar', 5),
		('Judge', 'Classic Hybrid', 'DYNAMIC DISCS', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Blue Bar', 5),
		('Judge', 'Classic Hybrid', 'DYNAMIC DISCS', 173, 2, 4, 0, 1, 'Putter', 'Main Bag', 'Pink', 'Blue Bar', 7),
		('Judge', 'Classic Hybrid', 'DYNAMIC DISCS', 173, 2, 4, 0, 1, 'Putter', 'Main Bag', 'Pink', 'Blue Bar', 6),
		('Judge', 'Classic Hybrid', 'DYNAMIC DISCS', 173, 2, 4, 0, 1, 'Putter', 'Backup', 'Black', 'Blue Bar', 7),
		('Judge', 'Classic Blend', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Black Mini Owl', 6),
		('Judge', 'Classic Blend', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Black Mini Owl', 6),
		('Judge', 'Prime', 'DYNAMIC DISCS', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'Blue', 'Black Mini Owl', 5),
		('Judge', 'Prime', 'DYNAMIC DISCS', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'Blue', 'Black Mini Owl', 5),
		('Judge', 'Prime', 'DYNAMIC DISCS', 175, 2, 4, 0, 1, 'Putter', 'Collection', 'Blue', 'Gold Bar', 5),
		('Judge', 'Prime', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Red', 'Silver Misprint Bar', 6),
		('Judge', 'Prime', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Red', 'Silver Misprint Bar', 6),
		('Judge', 'Prime', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Red', 'Silver Misprint Bar', 6),
		('Judge', 'Prime', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Red', 'Silver Misprint Bar Glow Tape', 6),
		('Judge', 'Prime Burst', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Pink', 'Silver Misprint Bar', 5),
		('Judge', 'Prime Burst', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Pink', 'Silver Misprint Bar', 5),
        ('Judge', 'Classic Burst', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Collection', 'Yellow', 'Silver Misprint', 7),
		('Harp', 'BT Medium', 'WESTSIDE DISCS', 173, 4, 3, 0, 3, 'Putter', 'Main Bag', 'Blue', 'Pink Shatter DGPT', 7),
		('Harp', 'VIP Moonshine', 'WESTSIDE DISCS', 176, 4, 3, 0, 3, 'Putter', 'Main Bag', 'Green', 'Red Ricky 2x', 7),
		('Justice', 'Lucid Glimmer', 'DYNAMIC DISCS', 169, 5, 1, .5, 4, 'Mid-Range', 'Main Bag', 'Pink', 'Blue Lady Justice', 7),
		('EMAC Truth', 'Lucid-X Glimmer', 'DYNAMIC DISCS', 180, 5, 5, 0, 2, 'Mid-Range', 'Main Bag', 'Pink', '2021 TS', 7),
		('EMAC Truth', 'Lucid-X Moonshine', 'DYNAMIC DISCS', 180, 5, 5, 0, 2, 'Mid-Range', 'Main Bag', 'Pink', '2020 TS V4', 7),
		('Fuse', 'Opto-X Glimmer', 'LATITUDE 64°', 178, 5, 6, -1, 0, 'Mid-Range', 'Main Bag', 'Pink', '2021 TS V2', 7),
		('Fuse', 'Opto', 'LATITUDE 64°', 178, 5, 6, -1, 0, 'Mid-Range', 'Main Bag', 'Orange', 'Black Witch', 5),
		('Explorer', 'Gold Burst', 'LATITUDE 64°', 175, 7, 5, 0, 2, 'Fairway Driver', 'Main Bag', 'Orange', '2018 AM Match Play', 6),
		('Explorer', 'Opto-X Glimmer', 'LATITUDE 64°', 176, 7, 5, 0, 2, 'Fairway Driver', 'Main Bag', 'Pink', '2020 TS V3', 7),
		('Escape', 'Fuzion', 'DYNAMIC DISCS', 173, 9, 5, -1, 2, 'Control Driver', 'Main Bag', 'Red', 'Purple HE Good Energy', 7),
		('Hatchet', 'VIP', 'WESTSIDE DISCS', 169, 9, 6, -2, 1, 'Control Driver', 'Main Bag', 'Pink', 'Green Stock', 7),
		('Felon', 'Lucid-X', 'DYNAMIC DISCS', 176, 9, 3, 0.5, 4, 'Control Driver', 'Main Bag', 'Pink', '2019 TS', 6),
		('Felon', 'Lucid-X Glimmer', 'DYNAMIC DISCS', 176, 9, 3, 0.5, 4, 'Control Driver', 'Main Bag', 'Pink', '2021 EO TS', 6),
		('Trespass', 'Fuzion', 'DYNAMIC DISCS', 175, 12, 5, -0.5, 3, 'Distance Driver', 'Main Bag', 'White', 'Candy Cane DyeMax', 6),
		('Trespass', 'Hybrid', 'DYNAMIC DISCS', 173, 12, 5, -0.5, 3, 'Distance Driver', 'Main Bag', 'Pink', 'PMBF La Paz', 7),
		('Rive', 'Royal-Proto', 'LATITUDE 64°', 175, 13, 5, 0, 3.5, 'Distance Driver', 'Main Bag', 'Orange', 'Prototype', 6),
		('Rive', 'Grand', 'LATITUDE 64°', 175, 13, 5, 0, 3.5, 'Distance Driver', 'Main Bag', 'Blue', 'Silver Stock', 8),
		('Ballista Pro', 'Opto Air', 'LATITUDE 64°', 158, 14, 4, 0, 3, 'Distance Driver', 'Main Bag', 'Orange', 'Misprint Stock', 7),
		('Ballista Pro', 'Opto Moonshine', 'LATITUDE 64°', 176, 14, 4, 0, 3, 'Distance Driver', 'Main Bag', 'Pink', 'Gold Bar', 7),
		('Ballista Pro', 'Gold', 'LATITUDE 64°', 174, 14, 4, 0, 3, 'Distance Driver', 'Main Bag', 'White', 'P Hill DyeMax', 5),
		('Ballista', 'Opto', 'LATITUDE 64°', 169, 14, 5, -1, 3, 'Distance Driver', 'Main Bag', 'Orange', 'Stock', 5),
		('Ballista', 'Opto Sparkle', 'LATITUDE 64°', 174, 14, 5, -1, 3, 'Distance Driver', 'Main Bag', 'Orange', 'Fall Fling 2 2022', 8),
		('Fierce', 'Rubber Blend', 'DISCRAFT', 171, 3, 4, -2, 0, 'Putter', 'Emily', 'Purple', 'Blue Shatter Tron', 7),
		('Fierce', 'Rubber Blend', 'DISCRAFT', 171, 3, 4, -2, 0, 'Putter', 'Emily', 'Orange', 'Purple Shatter Tron', 7),
		('Fierce', 'Big Z', 'DISCRAFT', 171, 3, 4, -2, 0, 'Putter', 'Emily', 'Red', 'Rainbow Lion', 8),
		('Fierce', 'Big Z', 'DISCRAFT', 171, 3, 4, -2, 0, 'Putter', 'Emily', 'Red', 'Rainbow Lion', 10),
		('Luna', 'Big Z', 'DISCRAFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Yellow', 'Black PMB Luna', 9),
		('Luna', 'Big Z', 'DISCRAFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Yellow', 'Black PMB Luna', 8),
		('Luna', 'Z', 'DISCRAFT', NULL, 3, 3, 0, 3, 'Putter', 'Emily', 'White', 'Black PMB TS 2020', 8),
		('Luna', 'Z', 'DISCRAFT', 170, 3, 3, 0, 3, 'Putter', 'Emily', 'Pink', 'Black PMB TS 2020', 8),
		('Luna', 'Metallic Z', 'DISCRAFT', 170, 3, 3, 0, 3, 'Putter', 'Emily', 'Pink', 'Silver Flower PMB TS 2021', 9),
		('Luna', 'Metallic Z', 'DISCRAFT', 170, 3, 3, 0, 3, 'Putter', 'Emily', 'Pink', 'Silver Sparkle PMB TS 2021', 10),
		('Luna', 'Special Blend', 'DISCRAFT', NULL, 3, 3, 0, 3, 'Putter', 'Emily', 'Purple', 'Green Shatter First Run', 6),
		('Luna', 'Jawbreaker', 'DISCRAFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Purple', 'Blue JoeMez Armadillo', 8),
		('Luna', 'Jawbreaker', 'DISCRAFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Pink', 'Rainbow JoeMez Armadillo', 8),
		('Luna', 'Jawbreaker', 'DISCRAFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Blue', 'Wite Slomez JoeMez', 7),
		('Luna', 'Jawbreaker', 'DISCRAFT', NULL, 3, 3, 0, 3, 'Putter', 'Emily', 'Green', 'Rainbow Slomez JoeMez', 7),
		('Luna', 'Rubber Blend', 'DISCRAFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Green', 'Blue OTB UFO', 7),
		('Luna', 'Rubber Blend', 'DISCRAFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Grey', 'Rainbow PMB Stock', 7),
		('Luna', 'Rubber Blend', 'DISCRAFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Black', 'Rainbow PMB Stock', 6),
		('BangerGT', 'Crystal Flx Sparkle', 'DISCRAFT', NULL, 3, 3, 0, 3, 'Putter', 'Emily', 'Blue', 'Cheetah Ledgestone 2021', 8),
		('Fuse', 'Lucid-X', 'LATITUDE 64°', 180, 5, 6, -1, 0, 'Mid-Range', 'Backup', 'Pink', 'Silver 2020 TS V1', 7),
		('Fuse', 'Opto Sparkle', 'LATITUDE 64°', 175, 5, 6, -1, 0, 'Mid-Range', 'Collection', 'Clear', 'Pink 10 Year', 9),
		('Pure', 'Zero Hybrid', 'LATITUDE 64°', 174, 3, 3, -1, 1, 'Putter', 'Collection', 'White', 'Black Royal Box', 9),
		('Pure', 'Opto Sparkle', 'LATITUDE 64°', 174, 3, 3, -1, 1, 'Putter', 'Collection', 'Silver', 'Skull Decodye', 7),
		('Faith', 'Sense Prototype', 'LATITUDE 64°', 173, 2, 3, 0, 1, 'Putter', 'Collection', 'Pink', 'Black Royal Prototype', 8),
		('Destroyer', 'Shimmer Star', 'INNOVA DISC GOLF', 175, 12, 5, -1, 3, 'Distance Driver', 'Collection', 'Gold', 'USDGC 2020', 10),
		('Explorer', 'Opto Glimmer', 'LATITUDE 64°', 174, 7, 5, 0, 2, 'Fairway Driver', 'Collection', 'Clear', 'Boat Decodye Royal Box', 9),
		('EMAC Judge', 'Classic Blend', 'DYNAMIC DISCS', 173, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Blue First RunMini', 10),
		('Envy', 'Electron?', 'AXIOM DISCS', 170, 3, 3, 0, 2, 'Putter', 'Collection', 'Purple', 'MVP Disc Sports OPEN 2020', 8),
		('EMAC Truth', 'Lucid', 'DYNAMIC DISCS', 174, 5, 5, 0, 2, 'Mid-Range', 'Collection', 'Pink', '2021 DYNAMIC DISCSO Signed by PMB, EMM, HK', 9),
		('Hades', 'ESP', 'DISCRAFT', NULL, 12, 6, -3, 2, 'Distance Driver', 'Collection', 'Pink', 'Silver Money Prototype', 8),
		('Sol', 'Z', 'DISCRAFT', 173, 4, 5, -3, 0, 'Mid-Range', 'Emily', 'Yellow', 'Silver Stock', 6),
		('Judge', 'Fuzion', 'DYNAMIC DISCS', 176, 2, 4, 0, 1, 'Putter', 'Side Bag', 'Pink', 'Red PS Stock', 6),
		('Judge', 'Fluid', 'DYNAMIC DISCS', 173, 2, 4, 0, 1, 'Putter', 'Side Bag', 'Pink', 'Silver Star PS Signed by PS', 7),
		('Judge', 'Classic Hybrid', 'DYNAMIC DISCS', 173, 2, 4, 0, 1, 'Putter', 'Side Bag', 'Yellow', 'Purple Bar', 6),
		('Justice', 'Lucid Sparkle', 'DYNAMIC DISCS', 171, 5, 1, .5, 4, 'Mid-Range', 'Side Bag', 'Pink', 'White TT 2020 Van', 6),
		('Harp', 'Tournament', 'WESTSIDE DISCS', 173, 4, 3, 0, 3, 'Putter', 'Side Bag', 'Pink', 'Pink Kannel', 6),
		('EMAC Truth', 'Lucid-X Moonshine', 'DYNAMIC DISCS', 180, 5, 5, 0, 2, 'Mid-Range', 'Side Bag', 'Pink', '2020 TS V4', 7),
		('Fuse', 'Opto', 'LATITUDE 64°', 177, 5, 6, -1, 0, 'Mid-Range', 'Side Bag', 'Pink', 'Misprint Stock', 8),
		('Felon', 'Lucid Glimmer', 'DYNAMIC DISCS', 174, 9, 3, 0.5, 4, 'Control Driver', 'Side Bag', 'Pink', 'Blue HE OS', 6),
		('Trespass', 'Fuzion', 'DYNAMIC DISCS', 175, 12, 5, -0.5, 3, 'Distance Driver', 'Backup', 'White', 'Beaver Ranch DyeMax', 6),
		('Enforcer', 'Lucid Sparkle', 'DYNAMIC DISCS', 172, 12, 4, .5, 4, 'Distance Driver', 'Side Bag', 'Pink', 'Gold Stock', 7),
		('Zone', 'Jawbreaker', 'DISCRAFT', 168, 4, 3, 0, 3, 'Putter', 'Emily', 'Yellow', 'Black GMC ', 7),
		('Zone', 'Jawbreaker', 'DISCRAFT', 173, 4, 3, 0, 3, 'Putter', 'Emily', 'Purple', 'Silver Stock ', 7),
		('Zone', 'Z', 'DISCRAFT', 173, 4, 3, 0, 3, 'Putter', 'Emily', 'Pink', 'Silver Stock ', 7),
		('Zone', 'ESP', 'DISCRAFT', 173, 4, 3, 0, 3, 'Putter', 'Emily', 'Green', 'Blue Stock ', 8),
		('Zone', 'ESP', 'DISCRAFT', 173, 4, 3, 0, 3, 'Putter', 'Emily', 'Blue', 'Blue Stock ', 8),
		('Zone', 'UV Photon', 'DISCRAFT', 165, 4, 3, 0, 3, 'Putter', 'Emily', 'Grey', 'Blue FDN', 8),
		('Zone', 'UV Photon', 'DISCRAFT', 165, 4, 3, 0, 3, 'Putter', 'Emily', 'Grey', 'Blue FDN', 8),
		('Sol', 'Z', 'DISCRAFT', NULL, 4, 5, -3, 0, 'Mid-Range', 'Emily', 'Yellow', 'Blacl PP5x', 7),
		('Sol', 'Z', 'DISCRAFT', 173, 4, 5, -3, 0, 'Mid-Range', 'Emily', 'Yellow', 'Red First Run', 5),
		('Sol', 'Z Metallic', 'DISCRAFT', 173, 4, 5, -3, 0, 'Mid-Range', 'Emily', 'Green', 'Blue PP Triangle', 8),
		('Sol', 'Z Metallic', 'DISCRAFT', 173, 4, 5, -3, 0, 'Mid-Range', 'Emily', 'Grey', 'Blue PP Triangle', 9),
		('Sol', 'Z Metallic', 'DISCRAFT', 173, 4, 5, -3, 0, 'Mid-Range', 'Emily', 'Blue', 'Silver PP Triangle', 10),
		('BangerGT', 'Crystal Flx Sparkle', 'DISCRAFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Blue', 'Cheetah Ledgestone 2021', 9),
		('BangerGT', 'Jawbreaker', 'DISCRAFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Yellow', 'Silver Shatter Stock', 7),
		('BangerGT', 'Jawbreaker', 'DISCRAFT', 171, 3, 3, 0, 3, 'Putter', 'Emily', 'Purple', 'Green Stock', 8),
		('BangerGT', 'Ti Swirl', 'DISCRAFT', 173, 3, 3, 0, 3, 'Putter', 'Emily', 'Green', 'Green LDG 2020', 7),
		('BangerGT', 'X Soft', 'DISCRAFT', NULL, 3, 3, 0, 3, 'Putter', 'Emily', 'Orange', 'Silver Shatter', 6),
		('Harp', 'Origo Burst', 'WESTSIDE DISCS', 173, 4, 3, 0, 3, 'Putter', 'Backup', 'Pink', 'Misprint Stock', 6),
		('Harp', 'BT Moonshine', 'WESTSIDE DISCS', 175, 4, 3, 0, 3, 'Putter', 'Backup', 'Blue', 'Idelwild DGPT 2020', 6),
		('Harp', 'BT Hard', 'WESTSIDE DISCS', 175, 4, 3, 0, 3, 'Putter', 'Backup', 'White', 'DYNAMIC DISCS OPEN 2021', 6),
		('Justice', 'Lucid Sparkle', 'DYNAMIC DISCS', 175, 5, 1, .5, 4, 'Mid-Range', 'Backup', 'Pink', 'JR ME DG', 6),
		('Justice', 'Prime', 'DYNAMIC DISCS', 171, 5, 1, .5, 4, 'Mid-Range', 'Backup', 'Red', 'Stock', 6),
		('Warship', 'Tournament', 'WESTSIDE DISCS', 177, 5, 6, 0, 1, 'Mid-Range', 'Emily', 'White', 'Demon DyeMax', 7),
		('Warship', 'Tournament', 'WESTSIDE DISCS', 167, 5, 6, 0, 1, 'Mid-Range', 'Emily', 'White', 'Gold Stock Old Flight Numbers', 7),
		('Warship', 'VIP', 'WESTSIDE DISCS', 174, 5, 6, 0, 1, 'Mid-Range', 'Emily', 'White', 'Fly Guy', 8),
		('EMAC Truth', 'Moonshine', 'DYNAMIC DISCS', 178, 5, 5, 0, 2, 'Mid-Range', 'Backup', 'Clear', 'Red Stock', 7),
		('EMAC Truth', 'Moonshine', 'DYNAMIC DISCS', 178, 5, 5, 0, 2, 'Mid-Range', 'Emily', 'Clear', 'Red Stock', 7),
		('EMAC Truth', 'Fuzion Burst', 'DYNAMIC DISCS', 171, 5, 5, 0, 2, 'Mid-Range', 'Emily', 'Blue', 'Gold Stock', 6),
		('EMAC Truth', 'Lucid-X Glimmer', 'DYNAMIC DISCS', 174, 5, 5, 0, 2, 'Mid-Range', 'Emily', 'Blue', 'TS 2020 ', 6),
		('EMAC Truth', 'Lucid Sparkle', 'DYNAMIC DISCS', 172, 5, 5, 0, 2, 'Mid-Range', 'Backup', 'Pink', 'Gold Stock', 7),
		('EMAC Truth', 'Lucid Sparkle', 'Dynamic Discs', 171, 5, 5, 0, 2, 'Mid-Range', 'Backup', 'Red', 'Black SKIN$ MATCH 2019', 7),
		('Mako3', 'Star', 'INNOVA DISC GOLF', 177, 5, 5, 0, 0, 'Mid-Range', 'Emily', 'White', 'Misprint Stock', 7),
		('Shark', 'DX', 'INNOVA DISC GOLF', NULL, 4, 4, 0, 2, 'Mid-Range', 'Emily', 'Purple', 'Sugarbush', 6),
		('Condor', 'Star', 'INNOVA DISC GOLF', NULL, 3, 4, 0, 2, 'Mid-Range', 'Collection', 'White', 'Green Stock', 7),
		('Trust', 'Grand', 'LATITUDE 64°', 174, 5, 5, 0, 2, 'Mid-Range', 'Collection', 'Blue', 'Silver Prototype', 8),
		('Beetle', 'Opto', 'LATITUDE 64°', 174, 1, 7, -1, 0, 'Mid-Range', 'Collection', 'Pink', 'Blue LATITUDE 64° Skull', 7),
		('Drone', 'Big Z', 'DISCRAFT', NULL, 5, 3, 1, 4, 'Mid-Range', 'Emily', 'Green', 'Black Stock', 6),
		('Verdict', 'Lucid-X', 'DYNAMIC DISCS', 180, 5, 4, 0, 3.5, 'Mid-Range', 'Collection', 'Pink', 'TS 2020', 7),
		('Buzzz', 'Crystal', 'DISCRAFT', 177, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Green', 'Blue PP OTB Bee', 9),
		('Buzzz', 'Crystal', 'DISCRAFT', 177, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Clear', 'Pink PP OTB Bee', 9),
		('Buzzz', 'Z', 'DISCRAFT', NULL, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Green', 'Red PP TS 2020', 8),
		('Buzzz', 'Z', 'DISCRAFT', NULL, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Blue', 'Blue PP TS 2020', 8),
		('Buzzz', 'Z', 'DISCRAFT', NULL, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Green', 'Red PP TS 2020', 8),
		('Buzzz', 'Z', 'DISCRAFT', NULL, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Green', 'Wonderbread MU SF 2021', 7),
		('Buzzz', 'ESP', 'DISCRAFT', NULL, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Blue', 'NEADGC 20201', 8),
		('Buzzz', 'Crystal', 'DISCRAFT', 177, 5, 4, -1, 1, 'Mid-Range', 'Emily', 'Pink', 'Blue PP OTB Bee', 8),
		('Archer', 'Big Z', 'DISCRAFT', NULL, 5, 4, -4, 1, 'Mid-Range', 'Emily', 'Green', 'Oils Slick Stock', 7),
		('Reactor', 'Eclipse Glow', 'MVP Disc Sports', 176, 5, 5, -.5, 1.5, 'Mid-Range', 'Collection', 'Green', 'Silver EK ES 2021', 8),
		('Compass', 'Gold', 'LATITUDE 64°', 179, 5, 5, 0, 1, 'Mid-Range', 'Emily', 'White', 'Pizza Kitty DyeMax', 7),
		('Diamond', 'Gold Orbit', 'LATITUDE 64°', 151, 8, 6, -3, 1, 'Fairway Driver', 'Emily', 'Pink', 'Purple 10 Year', 7),
		('Diamond', 'Opto', 'LATITUDE 64°', 171, 8, 6, -3, 1, 'Fairway Driver', 'Emily', 'Blue', 'Green and Red Misprint', 8),
		('Diamond', 'Opto', 'LATITUDE 64°', 154, 8, 6, -3, 1, 'Fairway Driver', 'Emily', 'White', 'Blue Stock', 6),
		('Sapphire', 'Opto', 'LATITUDE 64°', 157, 10, 6, -2, 1.5, 'Control Driver', 'Emily', 'Pink', 'Blue Stock', 8),
		('Sapphire', 'Opto Sparkle', 'LATITUDE 64°', 155, 10, 6, -2, 1.5, 'Control Driver', 'Emily', 'Green', 'Green Reindeer', 8),
		('Sapphire', 'Gold', 'LATITUDE 64°', 159, 10, 6, -2, 1.5, 'Control Driver', 'Emily', 'Red', 'Blue Bear', 8),
		('Sapphire', 'Gold Burst', 'LATITUDE 64°', 163, 10, 6, -2, 1.5, 'Control Driver', 'Emily', 'Blue', 'Diamond', 8),
		('Ballista Pro', 'Opto Chameleon', 'LATITUDE 64°', 176, 14, 4, 0, 3, 'Distance Driver', 'Backup', 'White', 'Red Royal Box', 8),
		('Ballista', 'Opto-X Chameleon', 'LATITUDE 64°', 175, 14, 4, 0, 3, 'Distance Driver', 'Backup', 'Pink', 'Red Special', 8),
		('Ballista', 'Opto-X Chameleon', 'LATITUDE 64°', 175, 14, 4, 0, 3, 'Distance Driver', 'Backup', 'Pink', 'Red Special', 8),
		('River', 'Opto', 'LATITUDE 64°', 173, 7, 7, -1, 1, 'Fairway Driver', 'Collection', 'White', 'Black Misprint Stock', 8),
		('River', 'Opto', 'LATITUDE 64°', 171, 7, 7, -1, 1, 'Fairway Driver', 'Collection', 'White', 'White Misprint Stock', 8),
		('River', 'Opto Sparkle', 'LATITUDE 64°', 174, 7, 7, -1, 1, 'Fairway Driver', 'Emily', 'Red', 'Blue Stock', 8),
		('River', 'Opto-X', 'LATITUDE 64°', NULL, 7, 7, -1, 1, 'Fairway Driver', 'Collection', 'Pink', 'Red 10 Year', 8),
		('River', 'Opto-X', 'LATITUDE 64°', NULL, 7, 7, -1, 1, 'Fairway Driver', 'Collection', 'Pink', 'Green 10 Year', 7),
		('Hatchet', 'VIP', 'WESTSIDE DISCS', 176, 9, 6, -2, 1, 'Control Driver', 'Collection', 'White', 'Black Misptint Underworld', 9),
		('Musket', 'Lucid', 'LATITUDE 64°', 174, 10, 5, 0.5, 2, 'Control Driver', 'Collection', 'White', 'Purple Pirate', 8),
		('Musket', 'Lucid', 'LATITUDE 64°', 174, 10, 5, 0.5, 2, 'Control Driver', 'Collection', 'Green', 'Silver and Blue Misprint', 8),
		('Explorer', 'Opto', 'LATITUDE 64°', 175, 7, 5, 0, 2, 'Fairway Driver', 'Collection', 'White', 'Gold and Silver Misprint Stock', 9),
		('Explorer', 'Opto', 'LATITUDE 64°', 175, 7, 5, 0, 2, 'Fairway Driver', 'Collection', 'White', 'Gold and Silver Misprint Stock', 9),
		('Raider', 'Lucid', 'DYNAMIC DISCS', 176, 13, 5, -0.5, 3, 'Distance Driver', 'Collection', 'White', 'Blue Misprint Stock', 9),
		('Raider', 'Fuzion', 'DYNAMIC DISCS', 174, 13, 5, -0.5, 3, 'Distance Driver', 'Collection', 'Pink', 'Gold Yin Yang', 7),
		('Raider', 'Fuzion', 'DYNAMIC DISCS', 174, 13, 5, -0.5, 3, 'Distance Driver', 'Collection', 'Pink', 'Gold Yin Yang', 8),
		('Raider', 'Bio Fuzion', 'DYNAMIC DISCS', 173, 13, 5, -0.5, 3, 'Distance Driver', 'Collection', 'Pink', 'Silver Am Match Play', 5),
		('Judge', 'Fuzion', 'DYNAMIC DISCS', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Green Misprint Lucid', 9),
		('Judge', 'Fuzion', 'DYNAMIC DISCS', 174, 2, 4, 0, 1, 'Putter', 'Collection', 'White', 'Green Misprint Lucid', 9),
		('Pure', 'Zero Moonshine', 'LATITUDE 64°', 176, 3, 3, -1, 1, 'Putter', 'Collection', 'White', 'Red 2020 AM Match Play', 9),
		('Trespass', 'Fuzion', 'DYNAMIC DISCS', 174, 12, 5, -0.5, 3, 'Distance Driver', 'Backup', 'White', 'BB  Phill DyeMax', 7),
		('Trespass', 'Fuzion', 'Dynamic Discs', 175, 12, 5, -0.5, 3, 'Distance Driver', 'Backup', 'White', 'Baseball DyeMax', 9),
		('Trespass', 'Lucid', 'DYNAMIC DISCS', 173, 12, 5, -0.5, 3, 'Distance Driver', 'Backup', 'Pink', 'Gold Stock', 8),
		('Trespass', 'Lucid', 'DYNAMIC DISCS', 173, 12, 5, -0.5, 3, 'Distance Driver', 'Backup', 'Pink', 'Silver and Red Misprint Stock', 9),
		('Trespass', 'Lucid', 'DYNAMIC DISCS', 175, 12, 5, -0.5, 3, 'Distance Driver', 'Backup', 'White', 'Green Reindeer', 8),
		('Trespass', 'Lucid', 'DYNAMIC DISCS', 173, 12, 5, -0.5, 3, 'Distance Driver', 'Backup', 'Yellow', 'Purple Skull/Dogs', 7),
		('Trespass', 'Lucid', 'DYNAMIC DISCS', 175, 12, 5, -0.5, 3, 'Distance Driver', 'Backup', 'Blue', 'Wonderland Brewing', 6),
		('Trespass', 'Prime Burst', 'DYNAMIC DISCS', 175, 12, 5, -0.5, 3, 'Distance Driver', 'Backup', 'Pink', 'Green and Purple Misprint Stock', 9),
		('Explorer', 'Opto-X Moonshine', 'LATITUDE 64°', 175, 7, 5, 0, 2, 'Fairway Driver', 'Backup', 'Pink', 'Wiped 2020 TS V4', 8),
		('Explorer', 'Opto-X Glimmer', 'LATITUDE 64°', 176, 7, 5, 0, 2, 'Fairway Driver', 'Backup', 'Pink', '2020 TS V3', 8),
		('Explorer', 'Opto-X Glimmer', 'LATITUDE 64°', 175, 7, 5, 0, 2, 'Fairway Driver', 'Backup', 'Pink', '2020 TS V2', 8),
		('Explorer', 'Grip', 'LATITUDE 64°', 176, 7, 5, 0, 2, 'Fairway Driver', 'Backup', 'Pink', 'Blue Bar', 5),
		('Escape', 'Lucid', 'DYNAMIC DISCS', 175, 9, 5, -1, 2, 'Control Driver', 'Side Bag', 'Pink', 'Blue Stock', 6),
		('Escape', 'Prime Burst', 'DYNAMIC DISCS', 173, 9, 5, -1, 2, 'Control Driver', 'Backup', 'Pink', 'Red and Silver Misprint Stock', 6),
		('Escape', 'Prime Burst', 'DYNAMIC DISCS', 173, 9, 5, -1, 2, 'Control Driver', 'Backup', 'Pink', 'Red and Silver Misprint Stock', 6),
		('Escape', 'Prime Burst', 'DYNAMIC DISCS', 173, 9, 5, -1, 2, 'Control Driver', 'Backup', 'Blue', 'Red Stock', 5),
		('Raketen', 'Opto Hex', 'LATITUDE 64°', 169, 15, 4, -2, 3, 'Distance Driver', 'Collection','Blue', 'Stock', 5),
		('Raptor', 'Z', 'DISCRAFT', 171, 9, 4, 0, 3, 'Control Driver', 'Emily', 'Yellow', 'Silver Stock', 8),
		('Jade', 'Opto', 'LATITUDE 64°', 156, 9, 6, -2, 1, 'Control Driver', 'Emily', 'Blue', 'White DYNAMIC DISCSO 2021', 7),
		('TeeBird3', 'GStar', 'INNOVA DISC GOLF', 157, 8, 4, 0, 2, 'Fairway Driver', 'Emily', 'Green', 'Silver Stock', 8),
		('Leopard', 'GStar', 'INNOVA DISC GOLF', NULL, 6, 5, -2, 1, 'Fairway Driver', 'Emily', 'Orange', 'Multi Color Stock', 8),
		('Leopard', 'Star', 'INNOVA DISC GOLF', 172, 6, 5, -2, 1, 'Fairway Driver', 'Emily', 'Blue', 'Yellow Stock', 8),
		('Leopard', 'Pro', 'INNOVA DISC GOLF', 175, 6, 5, -2, 1, 'Fairway Driver', 'Emily', 'White', 'TyeDye', 4),
		('Leopard', 'Pro', 'INNOVA DISC GOLF', NULL, 6, 5, -2, 1, 'Fairway Driver', 'Emily', 'Blue', 'Faded Stock', 4),
		('Roadrunner', 'Star', 'INNOVA DISC GOLF', 149, 9, 5, -4, 1, 'Control Driver', 'Emily', 'Orange', 'Black GB Stock', 8),
		('Roadrunner', 'Star', 'INNOVA DISC GOLF', 170, 9, 5, -4, 1, 'Control Driver', 'Emily', 'Blue', 'Purple GB Stock', 7),
		('Roadrunner', 'Star', 'INNOVA DISC GOLF', 150, 9, 5, -4, 1, 'Control Driver', 'Emily', 'Yellow', 'Blue F2', 4),
		('Roadrunner', 'Champion', 'INNOVA DISC GOLF', 170, 9, 5, -4, 1, 'Control Driver', 'Emily', 'Red', 'Blue Wondervu', 8),
		('Sergeant', 'Lucid', 'DYNAMIC DISCS', 173, 11, 3, 0.5, 4, 'Distance Driver', 'Collection', 'Pink', 'Silver First Run', 6),		
		('Sergeant', 'Lucid', 'DYNAMIC DISCS', 173, 11, 3, 0.5, 4, 'Distance Driver', 'Collection', 'Orange', 'USA First Run', 8),
		('Grace', 'Royal-Proto', 'LATITUDE 64°', 173, 11, 6, -1, 2, 'Distance Driver', 'Collection', 'Orange', 'Prototype', 8),
		('Rival', 'Pinnacle', 'LEGACY DISCS', 175, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Pink', 'Blue Stock', 8),
		('Rival', 'Icon', 'LEGACY DISCS', 172, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Purple', 'Gold Stock', 7),
		('Undertaker', 'Z', 'DISCRAFT', NULL, 9, 5, -1, 2, 'Control Driver', 'Emily', 'Orange', 'Silver MG 2020 TS', 7),
		('Undertaker', 'ESP', 'DISCRAFT', NULL, 9, 5, -1, 2, 'Control Driver', 'Emily', 'Pink', 'Silver MU SF 2021', 7),
		('Maverick', 'Special Edition', 'DYNAMIC DISCS', 175, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Pink', 'Black Stock', 7),
		('Maverick', 'Lucid', 'DYNAMIC DISCS', 169, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Purple', 'Black and Silver Misprint Stock', 7),
		('Sapphire', 'Opto Chameleon', 'LATITUDE 64°', 157, 10, 6, -2, 1.5, 'Control Driver', 'Emily', 'Blue', 'Blue First Run', 8),
		('Culverin', 'Opto', 'LATITUDE 64°', 175, 9, 5, -.5, 3, 'Control Driver', 'Collection', 'Grey', 'Grey Stock', 7),
		('Culverin', 'Opto Air', 'LATITUDE 64°', 159, 9, 5, -.5, 3, 'Control Driver', 'Collection', 'Red', 'Purple Stock', 8),
		('War Horse', 'VIP', 'WESTSIDE DISCS', 170, 13, 4, 0, 4, 'Distance Driver', 'Collection', 'Blue', 'Green and Silver Misprint', 9),
		('Convict', 'Lucid', 'DYNAMIC DISCS', 174, 9, 5, -.5, 3, 'Control Driver', 'Collection', 'Yellow', 'Purple and BlueDisc Golf', 8),
		('Pioneer ', 'Gold Burst', 'LATITUDE 64°', 173, 9, 3, 0, 4, 'Control Driver', 'Collection', 'Blue', 'Silver and Purple Am Match Play', 8),
		('Hell Fire', 'Pro-Line', 'Disc Golf Association', 171, 10, 3, 0, 5, 'Control Driver', 'Collection', 'Blue', 'Pink DELA', 8),
		('Maverick', 'Lucid-X Chameleon', 'Dynamic Discs', 176, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Red', '2021 ZM TS', 7),
		('Maverick', 'Lucid', 'Dynamic Discs', 172, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Clear', 'Purple and Silver Misprint Stock', 7),
		('Maverick', 'Lucid', 'Dynamic Discs', 172, 7, 5, 0, 2, 'Fairway Driver', 'Emily', 'Clear', 'Purple and Silver Misprint Stock', 7),
		('Slammer', 'Lucid', 'Dynamic Discs', 174, 3, 2, 0, 3, 'Putter', 'Collection', 'Red', 'Gold Stock', 7),
		('Slammer', 'Classic Blend', 'Dynamic Discs', 175, 3, 2, 0, 3, 'Putter', 'Collection', 'Whie', 'Gold Stock', 5),
		('Breakout', 'Prime Burst', 'Dynamic Discs', 157, 8, 5, -1, 1.5, 'Fairway Driver', 'Collection', 'Pink', 'Silver Stock', 3),
		('Boatman', 'VIP', 'Dynamic Discs', 171, 11, 5, 0, 2, 'Distance Driver', 'Collection', 'Orange', 'Faded Stock', 6),
		('Lace', NULL, 'Vibram', 172, 14, 6, -1, 1, 'Distance Driver', 'Collection', 'Green', NULL, 4),
		('Vamp', NULL, 'Vibram', 158, 7, 5, -2, 1, 'Fairway Driver', 'Collection', 'White', NULL, 5),
		('Golem', ' StayPut', 'Divergent', 174, 4, 2, 0, 3.5, 'Putter', 'Collection', 'Black', 'White Stock', 8),
		('#2 Driver', 'Lightning Standard', 'Lightning Discs', NULL, 8, 5, -2, 2, 'Fairway Driver', 'Collection', 'Clear', 'Faded Blue Stock', 3),
		('Avenger SS', 'Z', 'Discraft', NULL, 10, 5, -3, 1, 'Control Driver', 'Collection', 'Orange', 'Black Stock', 9),
		('Reaper', 'Elite Z', 'Discraft', NULL, 8, 3, 0, 4, 'Fairway Driver', 'Collection', 'TyeDye', 'Silver Stock', 7),
		('Machete', 'Titanium', 'Discraft', NULL, 11, 4, 0, 4, 'Distance Driver', 'Collection', 'Blue', 'Open at Belton 2019', 9),
		('FLICK', 'Z', 'Discraft', 173, 12, 3, 1, 5, 'Distance Driver', 'Collection', 'Red', 'White Stock', 9),
		('Relay', 'Neutron', 'MVP Disc Sports', 158, 6, 5, -2, 1, 'Fairway Driver', 'Collection', 'White', 'PDisc Golf Association Membership', 9),
		('Destroyer', 'Star', 'INNOVA DISC GOLF', NULL, 12, 5, -1, 3, 'Distance Driver', 'Collection', 'Purple', 'Silver PMB 4x', 7),
		('Destroyer', 'Star', 'INNOVA DISC GOLF', 169, 12, 5, -1, 3, 'Distance Driver', 'Collection', 'White', 'Bottom Stamp Santa Cruz', 6),
		('Destroyer', NULL, 'INNOVA DISC GOLF', 175, 12, 5, -1, 3, 'Distance Driver', 'Collection', 'White', 'Dragons Breath Open 2018', 7),
		('Destroyer', 'Pro', 'INNOVA DISC GOLF', 168, 12, 5, -1, 3, 'Distance Driver', 'Collection', 'Orange', 'Gold Misprint', 7),
		('Firebird', 'Color Glow', 'INNOVA DISC GOLF', 175, 9, 3, 0, 4, 'Control Driver', 'Collection', 'Blue', 'Blue NS TS 2017', 6),
		('Valkyrie', 'Star', 'INNOVA DISC GOLF', 150, 9, 4, -2, 2, 'Control Driver', 'Collection', 'White', 'Pink Faded Stock', 6),
		('Katana', 'Blizzard Champion', 'INNOVA DISC GOLF', 168, 13, 5, -3, 3, 'Distance Driver', 'Collection', 'Yellow', 'Red Stock', 7),
		('Tern', 'Champion', 'INNOVA DISC GOLF', NULL, 12, 6, -3, 2, 'Distance Driver', 'Collection', 'Red', 'Faded Stock', 7),
		('Tern', 'Champion', 'INNOVA DISC GOLF', NULL, 12, 6, -3, 2, 'Distance Driver', 'Collection', 'Clear', 'Dyed', 7),
		('Wraith', 'DX', 'INNOVA DISC GOLF', 172, 11, 5, -1, 3, 'Distance Driver', 'Collection', 'Orange', 'Black Stock', 6),
		('Wraith', 'Pro', 'INNOVA DISC GOLF', 169, 11, 5, -1, 3, 'Distance Driver', 'Collection', 'yellow', 'Orange Stock', 6),
		('Boss', 'Pro', 'INNOVA DISC GOLF', 175, 13, 5, -1, 3, 'Distance Driver', 'Collection', 'White', 'Black Stock Gangster', 6),
		('Boss', 'Pro', 'INNOVA DISC GOLF', 175, 13, 5, -1, 3, 'Distance Driver', 'Collection', 'Black', 'Silver Stock', 7),
		('Boss', 'Blizzard Champion', 'INNOVA DISC GOLF', NULL, 13, 5, -1, 3, 'Distance Driver', 'Collection', 'Black', 'Silver DW Stock', 6),
		('Boss', 'Champion', 'INNOVA DISC GOLF', NULL, 13, 5, -1, 3, 'Distance Driver', 'Collection', 'TyeDye', 'Silver Stock', 6),
		('Cro', 'Star', 'INNOVA DISC GOLF', 175, 5, 3, 0, 2, 'Mid-Range', 'Collection', 'Yellow', 'Silver First Run', 7),
        ('D1', '750G', 'Prodigy Disc Golf', 174, 12, 5, 0, 3, 'Distance Driver', 'Collection', 'Yellow', 'MO TS 2020', 8),
		('Rive', 'Gold Line Orbit', 'Latitude 64°', 173, 13, 5, 0, 3.5, 'Distance Driver', 'Collection', 'Pink', 'Purple TT Tour Series 2022', 10)
        ;
